sudo: required
language: node_js
node_js: 
  - "0.12"
env:
    global:
         MONGO_URL: "mongodb://localhost:27017/meteor"
services:
 - mongodb
before_install:
  - "npm install -g gagarin"
install: 
  - "curl https://install.meteor.com | /bin/sh"
  - "meteor update"
script: 
  - "gagarin tests"
notifications:
  email: false
  slack:
    rooms:
      - smart-s:eCjA7fJqFdq7mRSC3hPgOwqa#traviscibuilds